export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POSTS = 'NEW_POSTS';


export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILUER = 'FETCH_USER_FAILUER';
export const FILTER_USER_DATA = 'FILTER_USER_DATA';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
 

export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const LOAD_DATA = "LOAD_DATA";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
export const LOAD_NEW_PAGE = "LOAD_NEW_PAGE";
export const LOAD_EXACT_PAGE = "LOAD_EXACT_PAGE";
// const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";